import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hideout Items | Menu", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        <header 
          className="top-0 w-full border-b-2 border-black px-8 py-4 flex justify-between mb-2"
        >
          <div>Logo</div>
          <div>Infos</div>
        </header>
        {children}
      </body>
    </html>
  );
}
